/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.List;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.Vehiculo;
import modelo.VehiculoDAO;

public class GestionVehiculos extends javax.swing.JFrame {
    private VehiculoDAO dao;
    private List<Vehiculo> listaVehiculos;
    private DefaultTableModel modeloTabla;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionVehiculos.class.getName());

    /**
     * Creates new form GestionVehiculos
     */
    public GestionVehiculos() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Gestión de Vehículos");
        dao = new VehiculoDAO();
        listaVehiculos = dao.cargarVehiculos();
        mostrarVehiculosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCaracteristicas = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPropietario = new javax.swing.JTextField();
        txtKilometraje = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblImagenVehiculo = new javax.swing.JLabel();
        btnCargarImagen = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        txtImagenes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 0, -1, 99));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel3.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, -1, -1));

        jLabel3.setText("ID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 153, -1, -1));

        jLabel4.setText("Marca");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 193, -1, -1));

        jLabel5.setText("Modelo");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 233, -1, -1));

        jLabel6.setText("Características");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 273, -1, -1));

        jLabel7.setText("Precio");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 313, -1, -1));

        jLabel9.setText("Año");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 361, -1, -1));

        jLabel10.setText("Descripción");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 397, -1, -1));

        jLabel11.setText("Propietario");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 437, -1, -1));

        jLabel13.setText("Kilometraje");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 477, -1, -1));

        txtCaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaracteristicasActionPerformed(evt);
            }
        });
        jPanel3.add(txtCaracteristicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 170, -1));
        jPanel3.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 170, -1));
        jPanel3.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 170, -1));
        jPanel3.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 170, -1));
        jPanel3.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 310, 171, -1));
        jPanel3.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 355, 171, -1));
        jPanel3.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 394, 170, -1));
        jPanel3.add(txtPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 434, 170, -1));
        jPanel3.add(txtKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 474, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Gestión de Vehículos");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 105, -1, -1));

        lblImagenVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagenVehiculo.setMaximumSize(new java.awt.Dimension(200, 150));
        lblImagenVehiculo.setMinimumSize(new java.awt.Dimension(200, 150));
        lblImagenVehiculo.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel3.add(lblImagenVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, -1, -1));

        btnCargarImagen.setText("Cargar imagen");
        btnCargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarImagenActionPerformed(evt);
            }
        });
        jPanel3.add(btnCargarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 318, -1, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 512, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 512, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 512, -1, -1));

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVehiculos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 543, 1343, -1));

        txtImagenes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(txtImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 359, 300, -1));

        jScrollPane4.setViewportView(jPanel3);

        jScrollPane3.setViewportView(jScrollPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaracteristicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaracteristicasActionPerformed

    private void btnCargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarImagenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar imagen del vehículo");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg"));

        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            String rutaDestino = "imagenes/" + archivo.getName();

            try {
                // Crea la carpeta si no existe
                Files.createDirectories(Paths.get("imagenes"));
                // Copia la imagen dentro de la carpeta del proyecto
                Files.copy(archivo.toPath(), Paths.get(rutaDestino), StandardCopyOption.REPLACE_EXISTING);

                txtImagenes.setText(rutaDestino);
                ImageIcon icon = new ImageIcon(rutaDestino);
                Image imagen = icon.getImage().getScaledInstance(lblImagenVehiculo.getWidth(), lblImagenVehiculo.getHeight(), Image.SCALE_SMOOTH);
                lblImagenVehiculo.setIcon(new ImageIcon(imagen));

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al cargar imagen: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCargarImagenActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            // Validar campos obligatorios
            if (txtId.getText().trim().isEmpty() ||
                txtMarca.getText().trim().isEmpty() ||
                txtModelo.getText().trim().isEmpty() ||
                txtPrecio.getText().trim().isEmpty() ||
                txtAnio.getText().trim().isEmpty() ||
                txtKilometraje.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.");
                return;
            }

            Vehiculo v = new Vehiculo();
            v.setId(txtId.getText().trim());
            v.setMarca(txtMarca.getText().trim());
            v.setModelo(txtModelo.getText().trim());
            v.setCaracteristicas(txtCaracteristicas.getText().trim());
            v.setDescripcion(txtDescripcion.getText().trim());
            v.setImagenes(txtImagenes.getText().trim());
            v.setPropietario(txtPropietario.getText().trim());

            // 🔹 Precio
            String precioTexto = txtPrecio.getText().trim().replace(",", "");
            try {
                double precio = Double.parseDouble(precioTexto);
                v.setPrecio(precio);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Formato de precio inválido. Use solo números, sin comas ni símbolos.");
                return;
            }

            // 🔹 Año
            try {
                int anio = Integer.parseInt(txtAnio.getText().trim());
                v.setAnio(anio);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Formato de año inválido. Use solo números enteros.");
                return;
            }

            // 🔹 Kilometraje
            String kmTexto = txtKilometraje.getText().trim().replace(",", "");
            try {
                double km = Double.parseDouble(kmTexto);
                v.setKilometraje(km);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Formato de kilometraje inválido. Use solo números, sin comas ni símbolos.");
                return;
            }

            // Agregar a la lista y guardar
            listaVehiculos.add(v);
            dao.guardarVehiculos(listaVehiculos);

            // Actualizar tabla y limpiar campos
            mostrarVehiculosEnTabla();
            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Vehículo registrado correctamente.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = tablaVehiculos.getSelectedRow();
    
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un vehículo de la tabla para actualizar.");
            return;
        }

        // Validar campos obligatorios
        if (txtMarca.getText().trim().isEmpty() ||
            txtModelo.getText().trim().isEmpty() ||
            txtPrecio.getText().trim().isEmpty() ||
            txtAnio.getText().trim().isEmpty() ||
            txtKilometraje.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.");
            return;
        }

        Vehiculo v = listaVehiculos.get(fila);
        v.setMarca(txtMarca.getText().trim());
        v.setModelo(txtModelo.getText().trim());
        v.setCaracteristicas(txtCaracteristicas.getText().trim());
        v.setDescripcion(txtDescripcion.getText().trim());
        v.setImagenes(txtImagenes.getText().trim());
        v.setPropietario(txtPropietario.getText().trim());

        // 🔹 Validar y asignar Precio
        String precioTexto = txtPrecio.getText().trim().replace(",", "");
        try {
            double precio = Double.parseDouble(precioTexto);
            v.setPrecio(precio);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Formato de precio inválido. Use solo números, sin comas ni símbolos.");
            return;
        }

        // 🔹 Validar y asignar Año
        String anioTexto = txtAnio.getText().trim();
        try {
            int anio = Integer.parseInt(anioTexto);
            v.setAnio(anio);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Formato de año inválido. Use solo números enteros.");
            return;
        }

        // 🔹 Validar y asignar Kilometraje
        String kmTexto = txtKilometraje.getText().trim().replace(",", "");
        try {
            double km = Double.parseDouble(kmTexto);
            v.setKilometraje(km);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Formato de kilometraje inválido. Use solo números, sin comas ni símbolos.");
            return;
        }

        // Guardar cambios
        dao.guardarVehiculos(listaVehiculos);
        mostrarVehiculosEnTabla();
        limpiarCampos();
        JOptionPane.showMessageDialog(this, "Vehículo actualizado correctamente.");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tablaVehiculos.getSelectedRow();
        if (fila >= 0) {
            int opcion = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de eliminar este vehículo?", "Confirmar eliminación", 
                JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                listaVehiculos.remove(fila);
                dao.guardarVehiculos(listaVehiculos);
                mostrarVehiculosEnTabla();
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Vehículo eliminado correctamente.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un vehículo para eliminar.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void limpiarCampos() {
        txtId.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtCaracteristicas.setText("");
        txtPrecio.setText("");
        txtAnio.setText("");
        txtDescripcion.setText("");
        txtImagenes.setText("");
        txtPropietario.setText("");
        txtKilometraje.setText("");
        lblImagenVehiculo.setIcon(null);
        lblImagenVehiculo.setText("Sin imagen");
    }

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new MenuAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    private void mostrarVehiculosEnTabla() {
        String[] columnas = {"ID", "Marca", "Modelo", "Características", "Precio", "Año", "Descripción", "Imágenes", "Propietario", "Kilometraje"};
        modeloTabla = new DefaultTableModel(columnas, 0);
        tablaVehiculos.setModel(modeloTabla);

        for (Vehiculo v : listaVehiculos) {
            Object[] fila = {
                v.getId(),
                v.getMarca(),
                v.getModelo(),
                v.getCaracteristicas(),
                v.getPrecio(),
                v.getAnio(),
                v.getDescripcion(),
                v.getImagenes(),
                v.getPropietario(),
                v.getKilometraje()
            };
            modeloTabla.addRow(fila);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionVehiculos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCargarImagen;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblImagenVehiculo;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtCaracteristicas;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtImagenes;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPropietario;
    // End of variables declaration//GEN-END:variables
}
