/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Vehiculo;
import modelo.VehiculoDAO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import java.util.List;


/**
 *
 * @author Asus
 */
public class MenuCatalogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCatalogo.class.getName());

    /**
     * Creates new form MenuCatalogo
     */
    public MenuCatalogo() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarCatalogo();
    }
    
   private void cargarCatalogo() {
        VehiculoDAO dao = new VehiculoDAO();
        List<Vehiculo> vehiculos = dao.cargarVehiculos();

        pnlCatalogo.removeAll(); // limpia antes de volver a cargar

        for (Vehiculo v : vehiculos) {

            JPanel card = new JPanel();
            card.setLayout(new BorderLayout());
            card.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
            card.setPreferredSize(new Dimension(220, 280));

            // ============================
            //   CARGAR IMAGEN CORRECTAMENTE
            // ============================

            JLabel lblImagen = new JLabel();
            lblImagen.setHorizontalAlignment(SwingConstants.CENTER);

            // Limpia la ruta que viene del CSV
            String nombreImg = v.getImagenes()
                    .replace("imagenes/", "")
                    .replace("imagenes\\", "");

            // Construye la ruta real donde está la imagen
            String ruta = System.getProperty("user.dir")
                    + File.separator + "imagenes"
                    + File.separator + nombreImg;

            System.out.println("Intentando cargar: " + ruta);

            File imagenFile = new File(ruta);

            if (imagenFile.exists()) {
                try {
                    Image img = ImageIO.read(imagenFile)
                            .getScaledInstance(200, 120, Image.SCALE_SMOOTH);
                    lblImagen.setIcon(new ImageIcon(img));
                } catch (IOException ex) {
                    lblImagen.setText("Error al leer la imagen");
                }
            } else {
                lblImagen.setText("Imagen no encontrada");
            }

            // ============================
            //   INFORMACIÓN DEL VEHÍCULO
            // ============================

            JLabel lblInfo = new JLabel("<html><b>" + v.getMarca() + " " + v.getModelo() + "</b><br>"
            + "Año: " + v.getAnio() + "<br>"
            + "Precio: $" + String.format("%,.0f", v.getPrecio())
            + "</html>");

            // ============================
            //   BOTÓN VER DETALLES
            // ============================

            JButton btnVerMas = new JButton("Ver detalles");
            btnVerMas.addActionListener(e -> {
                JOptionPane.showMessageDialog(this,
                        "Marca: " + v.getMarca() + "\nModelo: " + v.getModelo() +
                                "\nAño: " + v.getAnio() + "\nPrecio: $" + v.getPrecio() +
                                "\nDescripción: " + v.getDescripcion(),
                        "Detalles del vehículo", JOptionPane.INFORMATION_MESSAGE);
            });

            // Arma la tarjeta
            card.add(lblImagen, BorderLayout.NORTH);
            card.add(lblInfo, BorderLayout.CENTER);
            card.add(btnVerMas, BorderLayout.SOUTH);

            pnlCatalogo.add(card);
        }

        pnlCatalogo.revalidate();
        pnlCatalogo.repaint();
    }


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        scrollCatalogo = new javax.swing.JScrollPane();
        pnlCatalogo = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        lblTitulo.setText("Catálogo de Vehículos");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        scrollCatalogo.setViewportView(pnlCatalogo);

        getContentPane().add(scrollCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 670, 330));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuCliente menu = new MenuCliente();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuCatalogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlCatalogo;
    private javax.swing.JScrollPane scrollCatalogo;
    // End of variables declaration//GEN-END:variables
}
