/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class MenuCatalogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCatalogo.class.getName());

    /**
     * Creates new form MenuCatalogo
     */
    public MenuCatalogo() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblFotoMazda = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblFotoToyota = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblFotoRenauld = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblFotoHyundai = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Catalogo de vehiculos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFotoMazda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/018239_2010_Mazda_Mazda3 (3).jpg"))); // NOI18N
        lblFotoMazda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoMazdaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFotoMazdaMouseEntered(evt);
            }
        });
        jPanel3.add(lblFotoMazda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 250, 140));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFotoToyota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/WhatsApp Image 2025-11-08 at 8.29.44 PM (1).png"))); // NOI18N
        lblFotoToyota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoToyotaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblFotoToyota)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFotoToyota, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 250, 150));

        jLabel1.setText("Toyota Tacoma Trd Pro 2.4 White 2025.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jLabel2.setText("Mazda3 Grand Touring Sedán");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFotoRenauld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/WhatsApp Image 2025-11-08 at 8.29.45 PM (1).png"))); // NOI18N
        lblFotoRenauld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoRenauldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblFotoRenauld)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblFotoRenauld, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 250, 160));

        jLabel5.setText("Renault Logan 1.4 Entry Familier");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFotoHyundai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/WhatsApp Image 2025-11-08 at 8.29.45 PM (1) (1) (1).png"))); // NOI18N
        lblFotoHyundai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoHyundaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblFotoHyundai)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFotoHyundai, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 230, 150));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jLabel6.setText("Hyundai Veloster 1.6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFotoMazdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMazdaMouseClicked
       
       String marca = "Mazda";
    String modelo = "3 Sedán";
    String caracteristicas = "Motor 2.0L, Asientos de Cuero";
    String precio = "$8,500.00 USD";
    String anio = "2012";
    String descripcion = "Vehículo en excelentes condiciones, único dueño.";
    String kilometraje = "125,000 km";

    // 2. Formatear la información para el mensaje (Usando HTML para mejor formato si lo deseas)
    // El JOptionPane de Swing puede interpretar etiquetas HTML básicas para formato.
    String mensajeHTML = "<html>"
                       + "<h2>&#x1F697; Información Detallada del Vehículo</h2>"
                       + "<hr>"
                       + "<table>"
                       + "<tr><td><b>Marca:</b></td><td>" + marca + "</td></tr>"
                       + "<tr><td><b>Modelo:</b></td><td>" + modelo + "</td></tr>"
                       + "<tr><td><b>Año:</b></td><td>" + anio + "</td></tr>"
                       + "<tr><td><b>Kilometraje:</b></td><td>" + kilometraje + "</td></tr>"
                       + "<tr><td><b>Precio:</b></td><td><span style='color:green;'>" + precio + "</span></td></tr>"
                       + "</table>"
                       + "<br>"
                       + "<b>Características Principales:</b> " + caracteristicas
                       + "<br><br>"
                       + "<b>Descripción:</b> " + descripcion
                       + "</html>";

    // 3. Mostrar el JOptionPane
    JOptionPane.showMessageDialog(
        this,              // Componente padre (JFrame o JPanel actual)
        mensajeHTML,       // El mensaje con formato HTML
        "Detalles del " + marca + " " + modelo, // Título de la ventana
        JOptionPane.INFORMATION_MESSAGE // Tipo de mensaje
    );
    }//GEN-LAST:event_lblFotoMazdaMouseClicked

    private void lblFotoMazdaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMazdaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFotoMazdaMouseEntered

    private void lblFotoToyotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoToyotaMouseClicked
      String marca = "Toyota";
    String modelo = "Tacoma";
    String anio = "2025";
    String version = "TRD Pro 3.5";
    String color = "Blanco";
    String combustible = "Híbrido";
    String puertas = "5";
    String transmision = "Automática";
    String motor = "2.4L";
    String kilometraje = "0 km";
    String precio = "$65,000 USD"; // <--- VARIABLE DEL PRECIO AÑADIDA

    // 2. Formatear la información usando HTML para un mejor diseño en el JOptionPane
    String mensajeHTML = "<html>"
                       + "<h2>&#x1F69B; Toyota Tacoma TRD Pro 2025</h2>"
                       + "<hr>"
                       + "<table>"
                       // Fila 1: Marca y Modelo
                       + "<tr><td><b>Marca:</b></td><td>" + marca + "</td>"
                       + "<td><b>Modelo:</b></td><td>" + modelo + "</td></tr>"
                       // Fila 2: Año y Versión
                       + "<tr><td><b>Año:</b></td><td>" + anio + "</td>"
                       + "<td><b>Versión:</b></td><td>" + version + "</td></tr>"
                       // Fila 3: Motor y Transmisión
                       + "<tr><td><b>Motor:</b></td><td>" + motor + "</td>"
                       + "<td><b>Transmisión:</b></td><td>" + transmision + "</td></tr>"
                       // Fila 4: Color y Combustible
                       + "<tr><td><b>Color:</b></td><td>" + color + "</td>"
                       + "<td><b>Combustible:</b></td><td>" + combustible + "</td></tr>"
                       // Fila 5: Puertas y Kilometraje
                       + "<tr><td><b>Puertas:</b></td><td>" + puertas + "</td>"
                       + "<td><b>Kilometraje:</b></td><td><span style='color:red;'><b>" + kilometraje + "</b></span></td></tr>"
                       + "</table>"
                       + "<br>"
                       + "<b>Características Principales:</b> Vehículo nuevo, tecnología híbrida i-FORCE MAX."
                       + "<br><br>" // <--- SALTO DE LÍNEA PARA EL PRECIO
                       + "<b>Precio Estimado:</b> <span style='color:green; font-size:14px;'><b>" + precio + "</b></span>" // <--- PRECIO AÑADIDO Y DESTACADO
                       + "</html>";

    // 3. Mostrar el JOptionPane (el 'MessageBox')
    JOptionPane.showMessageDialog(
        this,              // Componente padre
        mensajeHTML,       // El mensaje formateado
        "Ficha Técnica - " + marca + " " + modelo, // Título de la ventana
        JOptionPane.INFORMATION_MESSAGE // Tipo de mensaje
    );
    }//GEN-LAST:event_lblFotoToyotaMouseClicked

    private void lblFotoRenauldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoRenauldMouseClicked
       
        String marca = "Renault";
    String modelo = "Logan";
    String anio = "2015";
    String version = "1.4 Entry Familier";
    String color = "Blanco";
    String combustible = "Gasolina";
    String puertas = "5";
    String transmision = "Mecánica";
    String motor = "1.4L";
    String carroceria = "Sedán";
    String kilometraje = "97.475 km";
    String precio = "$24,500,000 COP"; // Precio ficticio estimado

    // 2. Formatear la información usando HTML para un mejor diseño en el JOptionPane
    String mensajeHTML = "<html>"
                       + "<h2>&#x1F697; Ficha Técnica - Renault Logan 2015</h2>"
                       + "<hr>"
                       + "<table>"
                       // Fila 1: Marca y Modelo
                       + "<tr><td><b>Marca:</b></td><td>" + marca + "</td>"
                       + "<td><b>Modelo:</b></td><td>" + modelo + "</td></tr>"
                       // Fila 2: Año y Versión
                       + "<tr><td><b>Año:</b></td><td>" + anio + "</td>"
                       + "<td><b>Versión:</b></td><td>" + version + "</td></tr>"
                       // Fila 3: Motor y Transmisión
                       + "<tr><td><b>Motor:</b></td><td>" + motor + "</td>"
                       + "<td><b>Transmisión:</b></td><td>" + transmision + "</td></tr>"
                       // Fila 4: Combustible y Kilometraje
                       + "<tr><td><b>Combustible:</b></td><td>" + combustible + "</td>"
                       + "<td><b>Kilometraje:</b></td><td>" + kilometraje + "</td></tr>"
                       // Fila 5: Color y Puertas
                       + "<tr><td><b>Color:</b></td><td>" + color + "</td>"
                       + "<td><b>Puertas:</b></td><td>" + puertas + "</td></tr>"
                       + "</table>"
                       + "<br>"
                       + "<b>Carrocería:</b> " + carroceria
                       + "<br><br>"
                       + "<b>Precio Estimado:</b> <span style='color:green;'><b>" + precio + "</b></span>"
                       + "</html>";

    // 3. Mostrar el JOptionPane (el 'MessageBox' flotante)
    JOptionPane.showMessageDialog(
        this,              // Componente padre
        mensajeHTML,       // El mensaje formateado
        "Detalles del Renault Logan", // Título de la ventana
        JOptionPane.INFORMATION_MESSAGE // Tipo de mensaje
    );
    }//GEN-LAST:event_lblFotoRenauldMouseClicked

    private void lblFotoHyundaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoHyundaiMouseClicked
      String marca = "Hyundai";
    String modelo = "Veloster";
    String anio = "2014";
    String version = "1.6";
    String color = "Azul";
    String combustible = "Gasolina";
    String puertas = "4"; // *Nota: El Veloster es conocido por su diseño asimétrico de 3 puertas + maletero, pero se respeta el valor de 4.*
    String transmision = "Automática";
    String motor = "1.6L";
    String carroceria = "Hatchback";
    String kilometraje = "70.000 km";
    String precio = "$38,000,000 COP"; // Precio ficticio estimado

    // 2. Formatear la información usando HTML para un mejor diseño en el JOptionPane
    String mensajeHTML = "<html>"
                       + "<h2>&#x1F697; Ficha Técnica - Hyundai Veloster 2014</h2>"
                       + "<hr>"
                       + "<table>"
                       // Fila 1: Marca y Modelo
                       + "<tr><td><b>Marca:</b></td><td>" + marca + "</td>"
                       + "<td><b>Modelo:</b></td><td>" + modelo + "</td></tr>"
                       // Fila 2: Año y Versión
                       + "<tr><td><b>Año:</b></td><td>" + anio + "</td>"
                       + "<td><b>Versión:</b></td><td>" + version + "</td></tr>"
                       // Fila 3: Motor y Transmisión
                       + "<tr><td><b>Motor:</b></td><td>" + motor + "</td>"
                       + "<td><b>Transmisión:</b></td><td>" + transmision + "</td></tr>"
                       // Fila 4: Combustible y Kilometraje
                       + "<tr><td><b>Combustible:</b></td><td>" + combustible + "</td>"
                       + "<td><b>Kilometraje:</b></td><td>" + kilometraje + "</td></tr>"
                       // Fila 5: Color y Puertas
                       + "<tr><td><b>Color:</b></td><td>" + color + "</td>"
                       + "<td><b>Puertas:</b></td><td>" + puertas + "</td></tr>"
                       + "</table>"
                       + "<br>"
                       + "<b>Carrocería:</b> " + carroceria
                       + "<br><br>"
                       + "<b>Precio Estimado:</b> <span style='color:green;'><b>" + precio + "</b></span>"
                       + "</html>";

    // 3. Mostrar el JOptionPane (el 'MessageBox' flotante)
    JOptionPane.showMessageDialog(
        this,              // Componente padre
        mensajeHTML,       // El mensaje formateado
        "Detalles del Hyundai Veloster", // Título de la ventana
        JOptionPane.INFORMATION_MESSAGE // Tipo de mensaje
    );
    }//GEN-LAST:event_lblFotoHyundaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuCatalogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblFotoHyundai;
    private javax.swing.JLabel lblFotoMazda;
    private javax.swing.JLabel lblFotoRenauld;
    private javax.swing.JLabel lblFotoToyota;
    // End of variables declaration//GEN-END:variables
}
