/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.io.FileWriter; 
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException; 
import java.text.SimpleDateFormat; 
import java.util.logging.Level; 
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class MenuCita extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCita.class.getName());

    /**
     * Creates new form MenuCita
     */
    public MenuCita() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(650, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAreaPara = new javax.swing.JTextField();
        txtNombreCompleto = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnEnviarSolicitud = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre completo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 38, 119, -1));

        jLabel2.setText("Telefono");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 86, 100, -1));

        jLabel3.setText("Correo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 134, 100, -1));

        jLabel4.setText("Fecha ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 188, 100, -1));
        getContentPane().add(txtAreaPara, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 250, 249, 81));
        getContentPane().add(txtNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 38, 249, 36));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 86, 249, 36));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 134, 249, 36));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 188, 249, 36));

        jLabel5.setText("Para");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 250, 100, -1));

        btnEnviarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ic_send_128_28719.png"))); // NOI18N
        btnEnviarSolicitud.setText("Enviar solicitud");
        btnEnviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, 50));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/4115235-exit-logout-sign-out_114030.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 150, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarSolicitudActionPerformed
       
        
       String nombre = txtNombreCompleto.getText().trim();
    String telefono = txtTelefono.getText().trim();
    String correo = txtCorreo.getText().trim();
    String fechaIngresada = txtFecha.getText().trim(); 
    String descripcion = txtAreaPara.getText().trim(); 

    // 2. VALIDACIÓN DE CAMPOS VACÍOS (Tu lógica es correcta)
    if (nombre.isEmpty() || telefono.isEmpty() || correo.isEmpty() || fechaIngresada.isEmpty() || descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Por favor, complete todos los campos de la solicitud.",
                "Campos Incompletos",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

   
    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
    formatoFecha.setLenient(false);

    try {
        formatoFecha.parse(fechaIngresada);
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this,
                "El formato de la fecha es incorrecto. Use el formato AAAA-MM-DD (ej: 2025-12-31).",
                "Error de Formato",
                JOptionPane.ERROR_MESSAGE);
        return; 
    }

   
    
 
    final String RUTA_ARCHIVO_CITAS = "src/data/solicitudes.csv"; 
    
   
    String descripcionLimpia = descripcion.replace('\n', ' ').replace(',', ';');
    
    // Formato CSV (5 campos separados por coma)
    String lineaCSV = nombre + "," + telefono + "," + correo + "," + fechaIngresada + "," + descripcionLimpia;

    try (

        FileWriter fileWriter = new FileWriter(RUTA_ARCHIVO_CITAS, true); 
        PrintWriter printWriter = new PrintWriter(fileWriter)
    ) {
        printWriter.println(lineaCSV);
        
        JOptionPane.showMessageDialog(this,
                "Solicitud de cita agendada y guardada correctamente.",
                "Envío Exitoso",
                JOptionPane.INFORMATION_MESSAGE);
        
      
        limpiarCampos(); 
        
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this,
                "Error al guardar la solicitud en el archivo: " + e.getMessage(),
                "Error de Archivo",
                JOptionPane.ERROR_MESSAGE);
    }
}


private void limpiarCampos() {
    txtNombreCompleto.setText("");
    txtTelefono.setText("");
    txtCorreo.setText("");
    txtFecha.setText("");
    txtAreaPara.setText("");

 
    }//GEN-LAST:event_btnEnviarSolicitudActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        
        try {
        
            MenuCliente menuCliente = new MenuCliente();
            
            
            menuCliente.setVisible(true);
            
           
            this.setVisible(false);
            
        } catch (Exception e) {
        
            JOptionPane.showMessageDialog(this,
                    "Error al volver al menú principal.", 
                    "Error de Navegación",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Error al abrir MenuCliente desde MenuCita", e);
        }
    
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuCita().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEnviarSolicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAreaPara;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
