/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter; 
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList; 
import java.util.List; 
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class MenuMisCitas extends javax.swing.JFrame {
    
    private DefaultTableModel modeloTabla;
    // Asegúrate de que esta ruta coincida con donde guardaste el archivo
    private final String RUTA_ARCHIVO_CITAS = "src/data/solicitudes.csv";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuMisCitas.class.getName());

    /**
     * Creates new form MenuMisCitas
     */
    public MenuMisCitas() {
        initComponents();
        configurarTabla();
        this.setResizable(false);
        this.setSize(800, 400);
    }
    
    private void configurarTabla() {
       
        modeloTabla = new DefaultTableModel() {
             // Opcional: Esto hace que las celdas de la tabla no sean editables
             @Override
             public boolean isCellEditable(int row, int column) {
                 return false;
             }
        };
        
        modeloTabla.addColumn("Nombre Completo");
        modeloTabla.addColumn("Teléfono");
        modeloTabla.addColumn("Correo");
        modeloTabla.addColumn("Fecha");
        modeloTabla.addColumn("Para"); 
        
        // Asigna el modelo a tu JTable
        tablaCitas.setModel(modeloTabla);
    }
    
    
    private void cargarDatosCSV() {
        
        modeloTabla.setRowCount(0); 

        try (
          
            BufferedReader br = new BufferedReader(new FileReader(RUTA_ARCHIVO_CITAS))
        ) {
            String linea;
            
            
            while ((linea = br.readLine()) != null) {
               
                
                String[] datos = linea.split(",", -1); 
                
                
                if (datos.length == 5) { 
                    modeloTabla.addRow(datos);
                } else {
                   
                     System.err.println("Línea CSV con formato incorrecto (saltada): " + linea);
                }
            }
        } catch (IOException e) {
           
            JOptionPane.showMessageDialog(this,
                    "Error al leer el archivo de citas: " + RUTA_ARCHIVO_CITAS + "\n" + e.getMessage(),
                    "Error de Carga de Datos",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Error al cargar datos CSV: {0}", e.getMessage());
        }
    }
    
    private void eliminarCitaCSV() {
   
        int totalFilas = modeloTabla.getRowCount();
        List<String> lineasConservar = new ArrayList<>(); 
        
   
        for (int i = 0; i < totalFilas; i++) {
            int filaAEliminar = 0;
            if (i != filaAEliminar) {
        
                StringBuilder lineaCSV = new StringBuilder();
                for(int j = 0; j < modeloTabla.getColumnCount(); j++) {
                    lineaCSV.append(modeloTabla.getValueAt(i, j));
                    if (j < modeloTabla.getColumnCount() - 1) {
                        lineaCSV.append(",");
                    }
                }
                lineasConservar.add(lineaCSV.toString());
            }
        }

     
        try (
            
            FileWriter fileWriter = new FileWriter(RUTA_ARCHIVO_CITAS, false); 
            PrintWriter printWriter = new PrintWriter(fileWriter)
        ) {
            for (String linea : lineasConservar) {
                printWriter.println(linea);
            }
            
          
            JOptionPane.showMessageDialog(this,
                    "La cita ha sido cancelada y eliminada correctamente.",
                    "Cancelación Exitosa",
                    JOptionPane.INFORMATION_MESSAGE);
            
          
            cargarDatosCSV(); 

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al reescribir el archivo de citas: " + e.getMessage(),
                    "Error de Archivo",
                    JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Error al eliminar la línea CSV: {0}", e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        btnMostrarcita = new javax.swing.JButton();
        btnCancelarCita = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre Completo", "Telefono", "Correo", "Fecha", "Para"
            }
        ));
        jScrollPane1.setViewportView(tablaCitas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 540, 170));

        btnMostrarcita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/3844441-eye-see-show-view-watch_110305.png"))); // NOI18N
        btnMostrarcita.setText("Mostrar cita");
        btnMostrarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarcitaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, 40));

        btnCancelarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancel_circle_close_delete_discard_file_x_icon_123219.png"))); // NOI18N
        btnCancelarCita.setText("Cancelar cita");
        btnCancelarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCitaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 213, 140, 40));

        jLabel1.setFont(new java.awt.Font("Roboto Mono", 2, 24)); // NOI18N
        jLabel1.setText("Mis citas  ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarcitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarcitaActionPerformed
       
        
        
        
        cargarDatosCSV();
    }//GEN-LAST:event_btnMostrarcitaActionPerformed

    private void btnCancelarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCitaActionPerformed
        
        
        eliminarCitaCSV();
    }//GEN-LAST:event_btnCancelarCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuMisCitas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCita;
    private javax.swing.JButton btnMostrarcita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCitas;
    // End of variables declaration//GEN-END:variables

}